CREATE TABLE roles (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
firstname VARCHAR(50),
lastname VARCHAR (50),
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(250) NOT NULL,
role_id BIGINT NOT NULL,
birth_date DATE,
FOREIGN KEY (role_id) REFERENCES roles(id)
);

